# Jykell configuration
markdown: redcarpet
highlight: pygments
paginate: 5

# Website info
name: 'Finding My Way of Joozo'
description: "I'm Joozo, Here is my new home. and you ?"

# Author's info
author: 'Joozo Zhao'
# edit 'categories' in the front matter of every post to match this username
username: joozo
bio: '一个脱离了低级趣味的人，一个有素质的人，一个有利于人民的人，一个造福万代的人！'
location: 'Beijing, China'
url: 'http://joozo.net/'
image: 'assets/images/casper.png'

short_url: 'joozo.net'
google_analytics: UA-71355287-1
disqus: joozonet
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: joozo
repo: joozo.net
branch: gh-pages
relative_source: ../
production_url:  http://joozo.net/
source_url:      https://github.com/joo-studio/joozo.net/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
